# path for item data
item_path: data/item.csv
# path for user data
user_path: data/user_25+1anchor.csv
# path for relationship data
relationship_path: data/relationship_25+1anchor.csv
# path for save interaction records
interaction_path: data/interaction.csv
# directory name for faiss index
index_name: data/faiss_index
# simulator directory name for saving and restoring
simulator_dir: data/simulator
# simulator restoring name
simulator_restore_file_name: 
# recommender system model
rec_model: Random
# number of epochs
epoch: 30
# number of agents, which cannot exceed the number of user in user.csv
agent_num: 10
# number of items to be recommended in one page
page_size: 5
# temperature for LLM
temperature: 0.3
# maximum number of tokens for LLM
max_token: 2048
# execution mode, serial or parallel
execution_mode: serial
# time interval for action of agents. The form is a number + a single letter, and the letter may be s, m, h, d, M, y
interval: 5h
# name of LLM model custom, gpt-3.5
llm: gpt-3.5
# number of max retries for LLM API
max_retries: 3
# verbose mode
verbose: True
# threshold for agent num
active_agent_threshold: 100
# method for choose agent to be active, random, sample, or marginal
active_method: random
# propability for agent to be active
active_prob: 1
# memory for recagent, recagent or none
recagent_memory: recagent
# whether to add role play
play_role: False
# list of api keys for LLM API
api_keys:
  - sk-nllqSQZXUcE0KocTB28904481846487bA2FfF82a9039Ca03
  # - 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


